export const SOFASCORE_ENDPOINTS = {
  search: { path: "search", ttl: 300 },
  "categories/list": { path: "categories/list", ttl: 86_400 },
  "categories/list-live": { path: "categories/list-live", ttl: 60 },
  "auto-complete": { path: "auto-complete", ttl: 300 },
  "sports/list": { path: "sports/list", ttl: 86_400 },

  "teams/detail": { path: "teams/detail", ttl: 3_600 },
  "teams/get-logo": { path: "teams/get-logo", ttl: 86_400, binary: true },
  "teams/get-performance": { path: "teams/get-performance", ttl: 1_800 },
  "teams/get-transfers": { path: "teams/get-transfers", ttl: 3_600 },
  "teams/get-squad": { path: "teams/get-squad", ttl: 1_800 },
  "teams/get-rankings": { path: "teams/get-rankings", ttl: 3_600 },
  "teams/get-tournaments": { path: "teams/get-tournaments", ttl: 86_400 },
  "teams/get-near-events": { path: "teams/get-near-events", ttl: 300 },
  "teams/get-statistics-seasons": { path: "teams/get-statistics-seasons", ttl: 86_400 },
  "teams/get-ranks": { path: "teams/get-ranks", ttl: 3_600 },
  "teams/get-statistics": { path: "teams/get-statistics", ttl: 1_800 },
  "teams/get-player-statistics-seasons": { path: "teams/get-player-statistics-seasons", ttl: 86_400 },
  "teams/get-player-statistics": { path: "teams/get-player-statistics", ttl: 1_800 },
  "teams/get-last-matches": { path: "teams/get-last-matches", ttl: 300 },
  "teams/get-next-matches": { path: "teams/get-next-matches", ttl: 300 },
  "teams/get-driver-career-history": { path: "teams/get-driver-career-history", ttl: 86_400 },
  "teams/get-stage-seasons": { path: "teams/get-stage-seasons", ttl: 86_400 },
  "teams/get-stage-season-races": { path: "teams/get-stage-season-races", ttl: 86_400 },

  "players/detail": { path: "players/detail", ttl: 3_600 },
  "players/get-image": { path: "players/get-image", ttl: 86_400, binary: true },
  "players/get-characteristics": { path: "players/get-characteristics", ttl: 86_400 },
  "players/get-ratings": { path: "players/get-ratings", ttl: 1_800 },
  "players/get-attribute-overviews": { path: "players/get-attribute-overviews", ttl: 1_800 },
  "players/get-national-team-statistics": { path: "players/get-national-team-statistics", ttl: 3_600 },
  "players/get-transfer-history": { path: "players/get-transfer-history", ttl: 86_400 },
  "players/get-last-year-summary": { path: "players/get-last-year-summary", ttl: 3_600 },
  "players/get-statistics-seasons": { path: "players/get-statistics-seasons", ttl: 86_400 },
  "players/get-all-statistics": { path: "players/get-all-statistics", ttl: 3_600 },
  "players/get-statistics": { path: "players/get-statistics", ttl: 1_800 },
  "players/get-last-matches": { path: "players/get-last-matches", ttl: 300 },
  "players/get-next-matches": { path: "players/get-next-matches", ttl: 300 },

  "managers/get-career-history": { path: "managers/get-career-history", ttl: 86_400 },
  "managers/detail": { path: "managers/detail", ttl: 3_600 },
  "managers/get-image": { path: "managers/get-image", ttl: 86_400, binary: true },
  "managers/get-last-matches": { path: "managers/get-last-matches", ttl: 300 },
  "managers/get-next-matches": { path: "managers/get-next-matches", ttl: 300 },

  "tournaments/list": { path: "tournaments/list", ttl: 86_400 },
  "tournaments/detail": { path: "tournaments/detail", ttl: 3_600 },
  "tournaments/get-logo": { path: "tournaments/get-logo", ttl: 86_400, binary: true },
  "tournaments/get-trending-events": { path: "tournaments/get-trending-events", ttl: 300 },
  "tournaments/get-featured-events": { path: "tournaments/get-featured-events", ttl: 300 },
  "tournaments/get-scheduled-events": { path: "tournaments/get-scheduled-events", ttl: 300 },
  "tournaments/get-live-events": { path: "tournaments/get-live-events", ttl: 30 },
  "tournaments/get-seasons": { path: "tournaments/get-seasons", ttl: 86_400 },
  "tournaments/get-top-players": { path: "tournaments/get-top-players", ttl: 1_800 },
  "tournaments/get-top-teams": { path: "tournaments/get-top-teams", ttl: 1_800 },
  "tournaments/get-rounds": { path: "tournaments/get-rounds", ttl: 3_600 },
  "tournaments/get-team-of-the-week-rounds": { path: "tournaments/get-team-of-the-week-rounds", ttl: 3_600 },
  "tournaments/get-team-of-the-week": { path: "tournaments/get-team-of-the-week", ttl: 1_800 },
  "tournaments/get-player-statistics": { path: "tournaments/get-player-statistics", ttl: 1_800 },
  "tournaments/get-standings": { path: "tournaments/get-standings", ttl: 1_800 },
  "tournaments/get-media": { path: "tournaments/get-media", ttl: 1_800 },
  "tournaments/get-cuptrees": { path: "tournaments/get-cuptrees", ttl: 3_600 },
  "tournaments/get-last-matches": { path: "tournaments/get-last-matches", ttl: 300 },
  "tournaments/get-next-matches": { path: "tournaments/get-next-matches", ttl: 300 },

  "matches/detail": { path: "matches/detail", ttl: 300 },
  "matches/get-ai-insights": { path: "matches/get-ai-insights", ttl: 1_800 },
  "matches/get-lineups": { path: "matches/get-lineups", ttl: 300 },
  "matches/get-comments": { path: "matches/get-comments", ttl: 120 },
  "matches/get-incidents": { path: "matches/get-incidents", ttl: 120 },
  "matches/get-managers": { path: "matches/get-managers", ttl: 300 },
  "matches/get-votes": { path: "matches/get-votes", ttl: 120 },
  "matches/get-graph": { path: "matches/get-graph", ttl: 300 },
  "matches/get-statistics": { path: "matches/get-statistics", ttl: 300 },
  "matches/get-team-streaks": { path: "matches/get-team-streaks", ttl: 1_800 },
  "matches/get-best-players": { path: "matches/get-best-players", ttl: 300 },
  "matches/get-media": { path: "matches/get-media", ttl: 1_800 },
  "matches/get-tweets": { path: "matches/get-tweets", ttl: 300 },
  "matches/get-team-heatmap": { path: "matches/get-team-heatmap", ttl: 1_800 },
  "matches/get-shotmap": { path: "matches/get-shotmap", ttl: 300 },
  "matches/get-esport-games": { path: "matches/get-esport-games", ttl: 300 },
  "matches/get-player-statistics": { path: "matches/get-player-statistics", ttl: 300 },
  "matches/get-player-heatmap": { path: "matches/get-player-heatmap", ttl: 1_800 },
  "matches/get-all-odds": { path: "matches/get-all-odds", ttl: 300 },
  "matches/get-featured-odds": { path: "matches/get-featured-odds", ttl: 300 },
  "matches/get-h2h-events": { path: "matches/get-h2h-events", ttl: 3_600 },
  "matches/get-h2h": { path: "matches/get-h2h", ttl: 3_600 },

  "esport-games/get-lineups": { path: "esport-games/get-lineups", ttl: 300 },
  "esport-games/get-statistics": { path: "esport-games/get-statistics", ttl: 300 },
  "esport-games/get-rounds": { path: "esport-games/get-rounds", ttl: 300 },
  "esport-games/get-bans": { path: "esport-games/get-bans", ttl: 300 },

  "tvchannels/get-available-countries": { path: "tvchannels/get-available-countries", ttl: 86_400 },
  "tvchannels/list": { path: "tvchannels/list", ttl: 86_400 },
  "tvchannels/get-votes": { path: "tvchannels/get-votes", ttl: 300 },
  "tvchannels/get-schedules": { path: "tvchannels/get-schedules", ttl: 3_600 },

  "stages/get-scheduled-events": { path: "stages/get-scheduled-events", ttl: 300 },
  "stages/detail": { path: "stages/detail", ttl: 3_600 },
  "stages/get-substages": { path: "stages/get-substages", ttl: 3_600 },
  "stages/get-driver-performance": { path: "stages/get-driver-performance", ttl: 1_800 },
  "stages/get-standings": { path: "stages/get-standings", ttl: 1_800 },
  "stages/get-highlights": { path: "stages/get-highlights", ttl: 1_800 },
  "stages/get-races": { path: "stages/get-races", ttl: 300 },
  "stages/get-odds": { path: "stages/get-odds", ttl: 300 }
} as const;

export type SofaScoreEndpoint = keyof typeof SOFASCORE_ENDPOINTS;

export function isSofaScoreEndpoint(value: string): value is SofaScoreEndpoint {
  return value in SOFASCORE_ENDPOINTS;
}
